### ISSUE TITLE
Is it possible to censor some assignments?

### ISSUE THREAD

**Issue by miguelriemoliveira** [bmc/munkres#22]
Hello, 

I wanted to use this package to solve an assignment problem. The catch is that I have some particular combinations of assignments which should be forbidden or censored. 

For example, say we have matrix:

```
[ [1 3 5 1]
  [7 5 2 3]
  [3 8 2 3] ]
```
... but we "know" that we cannot assign row 0 to columns 0 and 3. Replacing the forbidden assignmens by nan values the matrix would be something like:

```
[ [NaN 3 5 NaN]
  [7 5 2 3]
  [3 8 2 3] ]
```

How can this be done? I have tried setting the forbidden elements to nan but sometimes I get an infinite loop inside the compute method ...

Setting the forbidden elements to very large values would also not work because I could still get a forbidden assignment if there is no alternative ...

Thanks in advance,

Miguel

**Comment by bmc** [comment]
Well, the algorithm wasn't specifically designed to solve that problem, if I recall correctly. (I wrote this package 9 years ago, as an assignment for a job interview, and I haven't used it very much since then, I have to admit.) It's certainly possible to modify the software to allow for unassignable (or forbidden) marker values, but it doesn't support that right now, and I don't really have a lot of time to add that feature.

**Comment by miguelriemoliveira** [comment]
Hi Brian,

Thanks for the feedback, and the honesty. I will try to implement this functionality and if I can I'll send a pull request.

Regards,

Miguel
